[book]
authors = ["CSBAOYAN"]
language = "zh"
multilingual = true
src = "src"
title = "CSBasicKnowledge"

[output.html]
mathjax-support = true
site-url = "/CSBasicKnowledge/"
git-repository-url = "https://github.com/CS-BAOYAN/CSBasicKnowledge"
edit-url-template = "https://github.com/CS-BAOYAN/CSBasicKnowledge/edit/main/{path}"